project 'Jekyll-Admin-Mac.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'Jekyll-Admin-Mac' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!  
  pod 'FontAwesomeIconFactory'
  pod 'AlamofireObjectMapper', '~> 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
